1.3. Editing Flat Pages
thinknetica-django-lab-02/Kategkate pull request #11
Opened 2021-03-24 07:56 UTC by Kategkate

Closes #6

2021-03-24 08:05 UTC, morgangt requested changes

2021-03-24 08:05 UTC, morgangt commented on bookme/posts/views.py
> +    template_name = 'newsroom.html'
добавьте к этим классам docstring  с коротким описанием за что отвечает этот класс 
что такое docstring можно почитать тут на русском
https://habr.com/ru/post/499358/
и в оригинале здесь 
https://www.python.org/dev/peps/pep-0257/

2021-03-24 13:00 UTC, Kategkate commented
Done.

2021-03-24 13:00 UTC, Kategkate commented on bookme/posts/views.py
> +    template_name = 'newsroom.html'
Done

2021-03-28 17:14 UTC, Kategkate commented
Changes has been done

2021-03-29 07:40 UTC, morgangt approved these changes

2021-03-29 10:29 UTC, merged